version: '3.8'
services:
  app:
    build: .
    container_name: appserver
    ports:
      - '3002:3002'
    command: npm run dev
    env_file:
      - .env
    environment:
      - NODE_ENV=development
      - USE_MONGO=${USE_MONGO}
    depends_on:
      - postgres
      - mongo
    networks:
      - app-network

  postgres:
    container_name: postgresserver
    image: postgres:16.0-alpine
    env_file:
      - .env
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  mongo:
    container_name: mongodbserver
    image: mongo:7.0.9-jammy
    env_file:
      - .env
    environment:
      - MONGO_INITDB_DATABASE=mongodb
    ports:
      - '27017:27017'
    volumes:
      - mongodata:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  pgdata:
  mongodata:
